---
all: 
    children:
          Routers:
                hosts:
                  centralRouter:
                    ansible_host: 127.0.0.1
                    ansible_port: 2200
                    ansible_private_key_file: /root/OTUS/Kazay/Nets/Nets/.vagrant/machines/centralRouter/virtualbox/private_key
                  office1router:
                      ansible_host: 127.0.0.1
                      ansible_port: 2201
                      ansible_private_key_file: /root/OTUS/Kazay/Nets/Nets/.vagrant/machines/office1router/virtualbox/private_key
                  office2router:
                      ansible_host: 127.0.0.1
                      ansible_port: 2202
                      ansible_private_key_file: /root/OTUS/Kazay/Nets/Nets/.vagrant/machines/office2router/virtualbox/private_key
                  inetRouter:
                      ansible_host: 127.0.0.1
                      ansible_port: 2222
                      ansible_private_key_file: /root/OTUS/Kazay/Nets/Nets/.vagrant/machines/inetRouter/virtualbox/private_key
          Servers:
                hosts:
                    centralServer:
                      ansible_host: 127.0.0.1
                      ansible_port: 2200
                      ansible_private_key_file: /root/OTUS/Kazay/Nets/Nets/.vagrant/machines/centralServer/virtualbox/private_key
                    office1srv:
                        ansible_host: 127.0.0.1
                        ansible_port: 2222
                        ansible_private_key_file: /root/OTUS/Kazay/Nets/Nets/.vagrant/machines/office1srv/virtualbox/private_key
                    office2srv:
                        ansible_host: 127.0.0.1
                        ansible_port: 2222
                        ansible_private_key_file: /root/OTUS/Kazay/Nets/Nets/.vagrant/machines/office2srv/virtualbox/private_key
